### ISSUE TITLE
Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by sequencerr** [LeM0-Dev/puppeteer-page-proxy#3]
https://github.com/Cuadrix/puppeteer-page-proxy/issues/103
```js
C:\****\node_modules\@lem0-packages\puppeteer-page-proxy\src\core\proxy.js:48
    const listeners = page.eventsMap.get(eventName);
                                     ^

TypeError: Cannot read properties of undefined (reading 'get')
    at removeRequestListener (C:\****\node_modules\@lem0-packages\puppeteer-page-proxy\src\core\proxy.js:48:38)
```

**Comment by alvinlys** [comment]
yes, same goes to me with puppeteer-core v21.11.0

**Comment by sequencerr** [comment]
> yes, same goes to me with puppeteer-core v21.11.0

check out https://github.com/grabslabs/puppeteer-page-proxy

**Comment by LeM0-Dev** [comment]
> https://github.com/Cuadrix/puppeteer-page-proxy/issues/103
> 
> ```js
> 
> C:\****\node_modules\@lem0-packages\puppeteer-page-proxy\src\core\proxy.js:48
> 
>     const listeners = page.eventsMap.get(eventName);
> 
>                                      ^
> 
> 
> 
> TypeError: Cannot read properties of undefined (reading 'get')
> 
>     at removeRequestListener (C:\****\node_modules\@lem0-packages\puppeteer-page-proxy\src\core\proxy.js:48:38)
> 
> ```

@sequencerr unless you provide code to replicate the issue (sad to have to mention this still in 2024) it wint be fixed

**Comment by LeM0-Dev** [comment]
> @LeM0-Dev Thank you for rethinking your language. I don't need help, I just want to help you for the sake of your fork.
> 
> The repro code as primitive as
> ```js
> import puppeteer from 'puppeteer';
> import useProxy from '@lem0-packages/puppeteer-page-proxy';
> const browser = await puppeteer.launch();
> const page = await browser.newPage();
> await useProxy(page, 'http://127.0.0.1:80');
> ```

Alright thanks. Will check

**Comment by senzacionale** [comment]
Haha why deleting links from other repository. Yours is also a fork. 😅😅😅

**Comment by LeM0-Dev** [comment]
Should be fixed now!
